replicaCount: 3

image:
  repository: ealen/echo-server
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: echo.local
  path: /
  pathType: Prefix

resources: {}